routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("pertanyaan", "PertanyaanController");

// // Create pertanyaan
// Route::get("/pertanyaan/create", "PertanyaanController@create");

// // Menampilkan data table pertanyaan di web
// Route::get("/pertanyaan", "PertanyaanController@index");

// // menyimpan data di table pertanyaan yg ada di DB
// Route::post("/pertanyaan", "PertanyaanController@store");

// // Menampilkan secara spesifik pertanyaan
// Route::get("/pertanyaan/{pertanyaan_id}", "PertanyaanController@show");

// // Menampilkan form untuk edit pertanyaan dengan id tertentu
// Route::get("/pertanyaan/{pertanyaan_id}/edit", "PertanyaanController@edit");

// // Update pertanyaan
// Route::put("/pertanyaan/{pertanyaan_id}", "PertanyaanController@update");

// // Delete Pertanyaan
// Route::delete("/pertanyaan/{pertanyaan_id}", "PertanyaanController@destroy");


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Jawaban.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Question;

class Jawaban extends Model
{
    protected $table = "jawaban";
}

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Jawaban;
use App\User;

class Question extends Model
{
    protected $table = "pertanyaan";

    public function jawaban_benar() {
        return $this->hasOne("App\Jawaban", "pertanyaan_id");
    }

    public function nama_author() {
        return $this->belongsTo("App\User", "user_id");
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function list_pertanyaan() {
        return $this->hasMany("App\Question");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Question;
use App\Jawaban;
use Auth;

class PertanyaanController extends Controller
{
    // autentikasi
    public function __construct() {
        $this->middleware('auth')->except(["index"]);
    }

    public function create() {
        return view("tampilan.create");
    }

    public function store(Request $request) {
        $request->validate([
            "judul" => 'bail|required|unique:pertanyaan',
            "isi" => 'required',
        ]);

        // $query = DB::table("pertanyaan")->insert([
        //     "judul" => $request["judul"],
        //     "isi" => $request["isi"]
        // ]);

        $store = new Question;
        $store->judul = $request["judul"];
        $store->isi = $request["isi"];

        // ngisi foreign key user_id
        $store->user_id = Auth::user()->id;
        $store->save();

        return redirect("/pertanyaan")->with("success", "Pertanyaan berhasil disimpan");
    }

    public function index() {
        // $display = DB::table("pertanyaan")->get(); // kalau di sql-> SELECT * FROM nama_table
        
        $user= Auth::user();
        // $display = Question::all();

        $display = $user->list_pertanyaan;
        // dd($display);
        return view("tampilan.index", compact("display"));
    }

    public function show($pertanyaan_id) {
        // $show = DB::table("pertanyaan")->where("id", $pertanyaan_id)->first();
        
        $show = Question::find($pertanyaan_id);

        // buat ngecek isi dari 
        //  
        return view("tampilan.show", compact("show"));
    }

    public function edit($pertanyaan_id) {
        // $show = DB::table("pertanyaan")->where("id", $pertanyaan_id)->first();
        
        $show = Question::find($pertanyaan_id);
        return view("tampilan.edit", compact("show"));
    }

    public function update($pertanyaan_id, Request $request) {
        $request->validate([
            "judul" => 'bail|required',
            "isi" => 'required',
        ]);

        // $update = DB::table("pertanyaan")
        //             ->where("id", $pertanyaan_id)
        //             ->update([
        //                 "judul" => $request["judul"],
        //                 "isi" => $request["isi"]
        //             ]);

        Question::where("id", $pertanyaan_id)->update([
            "judul" => $request["judul"],
            "isi" => $request["isi"]
        ]);
        
        return redirect("/pertanyaan")->with("success", "Pertanyaan berhasil di-update");
    }

    public function destroy($pertanyaan_id) {
        // $destroy = DB::table("pertanyaan")->where("id", $pertanyaan_id)->delete();
        
        Question::destroy($pertanyaan_id);
        return redirect("pertanyaan")->with("success", "Pertanyaan berhasil di-delete");
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Blank Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset("/adminLTE/plugins/fontawesome-free/css/all.min.css")}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset("adminLTE/dist/css/adminlte.min.css")}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  @include('layouts.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('layouts.partials.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{asset("/adminLTE/plugins/jquery/jquery.min.js")}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset("/adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js")}}"></script>
<!-- AdminLTE App -->
<script src="{{asset("/adminLTE/dist/js/adminlte.min.js")}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset("/adminLTE/dist/js/demo.js")}}"></script>

@stack('scripts')

</body>
</html>

resources/views/layouts/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset("/adminLTE/dist/img/user1-128x128.jpg")}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset("adminLTE/dist/img/user8-128x128.jpg")}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset("/adminLTE/dist/img/user3-128x128.jpg")}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/tampilan/create.blade.php
@extends('layouts.master')

@section('content')
<section class="mx-3 pt-3">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Buat Pertanyaan Baru</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" action="/pertanyaan" method="POST">
            @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="title">Judul</label>
              <input type="text" class="form-control" id="judul" name="judul" placeholder="Enter Judul" value="{{old("judul", "")}}">

              @error('judul')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="body">Isi</label>
            <input type="text" class="form-control" id="isi" name="isi" placeholder="Enter isi" value="{{old("isi", "")}}">
              
            @error('isi')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
              @enderror
            </div>
          </div>
          <!-- /.card-body -->
    
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Create</button>
            <a class="btn btn-primary ml-2" href="/pertanyaan" role="button">Go Back</a>
          </div>
        </form>
      </div>
</section>
@endsection

resources/views/tampilan/edit.blade.php
@extends('layouts.master')

@section('content')
<section class="mx-3 pt-3">
    <div class="card card-primary">
        <div class="card-header">
        <h3 class="card-title">Edit Pertanyaan {{$show->id}}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" action="/pertanyaan/{{$show->id}}" method="POST">
            @csrf
            @method("PUT")
          <div class="card-body">
            <div class="form-group">
              <label for="judul">Judul</label>
              <input type="text" class="form-control" id="judul" name="judul" placeholder="Enter Judul" value="{{old("judul", $show->judul)}}">

              @error('judul')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="isi">Isi</label>
              <input type="text" class="form-control" id="isi" name="isi" placeholder="Enter Isi" value="{{old("isi", $show->isi)}}">
              @error('isi')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
              @enderror
            </div>
          </div>
          <!-- /.card-body -->
    
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-primary ml-2" href="/pertanyaan" role="button">Go Back</a>
          </div>
        </form>
      </div>
</section>
@endsection

resources/views/tampilan/index.blade.php
@extends('layouts.master')

@section('content')
<section class="mx-3 pt-3">
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Tabel Pertanyaan</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          @if (session("success"))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{session("success")}}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
          </div>
          @endif
          <a class="btn btn-primary mb-2" href={{route("pertanyaan.create")}} role="button">New Question</a>
          <table class="table table-bordered">
            <thead>                  
              <tr>
                <th style="width: 10px">#</th>
                <th>Judul</th>
                <th>Isi</th>
                <th style="width: 40px">Actions</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($display as $key => $post)
                  <tr>
                    <td>{{$key + 1}}</td>
                    <td>{{$post->judul}}</td>
                    <td>{{$post->isi}}</td>
                    <td class="d-flex">
                        <a class="btn btn-info btn-sm mr-2" href={{route("pertanyaan.show", ["pertanyaan"=>$post->id])}} role="button" st>Show</a>
                        <a class="btn btn-warning btn-sm mr-2" href={{route("pertanyaan.edit", ["pertanyaan"=>$post->id])}} role="button">Edit</a>
                        <form action={{route("pertanyaan.destroy", ["pertanyaan"=>$post->id])}} method="POST">
                            @csrf
                            @method("DELETE")
                            <input type="submit" value="Delete" class="btn btn-sm btn-danger">
                        </form>
                    </td>
                  </tr>
                  @empty
                    <tr>
                        <td colspan="4" align="center">No Questions</td>
                    </tr>
              @endforelse
            </tbody>
          </table>
        </div>
      </div>
</section>
@endsection

resources/views/tampilan/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="class mx-3 pt-3">
        {{-- <h4>Author: {{Auth::user()->name}}</h4> --}}
        <h4>Author: {{$show->nama_author->name}}</h4>
        <h4>Judul: {{$show->judul}}</h4>
        <h4>Isi: {{$show->isi}}</h4>
        <h4>Jawaban Benar: {{$show->jawaban_benar->isi}}</h4>
    </div>
@endsection